Layout
Our-Class-Bank/core-frontend pull request #1
Opened 2023-06-20 13:47 UTC by booyaChael

# Header & Side Bar 생성

2023-06-20 14:35 UTC, s0ojin requested changes

2023-06-20 14:35 UTC, s0ojin commented on src/assets/images/blueArrow.png
채을님 아이콘은 전부 svg로 사용하신다음 component로 사용하시는게 좋을 것 같습니다! png는 나중에 깨지는 경우도 있어서요! 또 svg로 사용하시면 컬러도 바꿔사용할 수 있어서 같은 아이콘을 여러번 사용할 수 있습니다!

2023-06-20 14:35 UTC, s0ojin commented on src/pages/layout/Header.tsx
아 저희가 폴더 구조를 아직 안정했네요! style은 src/style로 스타일을 분리하면 어떨까요?

2023-06-20 22:02 UTC, booyaChael commented on src/assets/images/blueArrow.png
저도 svg가 낫다고 생각하는데, 아이콘을 다운받은 flaticon에서 svg를 유료화해서요 ㅠ0ㅠ
아니면 혹시 다른 아이콘 사이트 사용하시는 것 있으신가요?

2023-06-21 00:24 UTC, s0ojin commented on src/assets/images/blueArrow.png
https://thenounproject.com/ 

여기서 무료로 svg 다운받으시면 워터마크 딸려오는데 피그마에서 아이콘만 따로 떼서 사용하실 수 있으실 거에요!

2023-06-21 00:56 UTC, booyaChael commented on src/pages/layout/Header.tsx
styled component를 style에 두자는 말씀이시죠? 네 좋습니다.

2023-06-21 01:01 UTC, s0ojin commented on src/pages/layout/Header.tsx
네 맞습니다!

2023-06-21 13:43 UTC, booyaChael commented on src/assets/images/blueArrow.png
svg로 변경하여 commit 하였습니다~

2023-06-22 14:16 UTC, merged